### ISSUE TITLE
Disable automatic update and (if possible) convert sync folder to relative path

### ISSUE THREAD

**Issue by cosmicdan** [naderi/owncloud-client-portable#5]
Hi,

Thanks a lot for this - allows me to take my sync'd folder with me to other PC's that have no admin or internet access. Couple of suggestions:

1) Disable automatic updates, since it doesn't work properly and tries to install on the host system. Can be done by editing the cfg file (maybe just provide a default skeleton with it already set?), see the official docs here (the last, Linux section, still relevant to us) - https://doc.owncloud.org/desktop/1.8/autoupdate.html

2) If possible, have the portable launcher convert the "0\Folders\1\localPath" key value to a relative path once the actual ownCloud app closes. I am not sure if this is possible without bringing in a second intermediate scripting tool.

Either way, thanks - works well :)

**Comment by naderi** [comment]
Done.
